### ISSUE TITLE
Error "Use of \??? doesn't match its definition. <argument> \??? LaTeX Error: Invalid operation (inf)*(0)"

### ISSUE THREAD

**Issue by Vasco-Da-Gama-png** [komascript/third-party-enhancements#2]
**Describe the bug**
When using the packages setspace & and scrhack and the command \setstretch{1.05} or \linespread{1.05} the following error occurs:

```
/workspaces/ITT LaTeX template/error.tex:14: Use of \??? doesn't match its definition.
<argument> \???  
      ! LaTeX Error: Invalid operation (inf)*(0)
l.14 }
```

When you call \LaTeX{} in a \footnote{}.

**Add code of a minimal working example**
Use LuaLaTeX with the latest TexLive Installation for the following minimal working example:

```latex
\documentclass{scrbook}
\usepackage{setspace}% Line spacing, used for title page
\usepackage{scrhack}% Fixes for packages incompatible with KOMA features
% \setstretch{1.05}
\linespread{1.05}

\begin{document}

This is a test document.
\footnote{%
    \LaTeX{}
    % \TeX{}
}

\end{document}
```

It results in the following messages from `log`-file:

```
/workspaces/ITT LaTeX template/error.tex:14: Use of \??? doesn't match its definition.
<argument> \???  
      ! LaTeX Error: Invalid operation (inf)*(0)
l.14 }
```

**Expected behavior**
No error to happen.

**Which TeX distribution?**
Latest TeX Live

**Comment by komascript** [comment]
First of all: Thank you for the report. I can confirm the issue.

Second: Please note, that `scrhack` is only a compatibility package for a deprecated KOMA-Script package. I recommend to use:
```latex
\documentclass{scrbook}
\usepackage{setspaceenhanced}% Line spacing, used for title page
\setstretch{1.05}
%\linespread{1.05}% works also

\begin{document}

This is a test document.%
\footnote{%
    \LaTeX{}
    % \TeX{}
}

\end{document}
```
instead. This is also the workaround for the issue, because it works without error message.

However the error is indeed in `setspaceenhanced` when using option `byselectfont`, which is default with `scrhack`.

**Comment by komascript** [comment]
Strange enough:
```latex
\documentclass{article}
\usepackage[byselectfont]{setspaceenhanced}
\setstretch{1.05}
\begin{document}
This is a test document with footnote.%
\footnote{%
  \fontsize{6}{0}\selectfont A
}
\end{document}
```
does not work, but
```latex
\documentclass{article}
\usepackage[byselectfont]{setspaceenhanced}
\setstretch{1.05}
\begin{document}
This is a test document with footnote.%

{
\footnotesize
  \fontsize{6}{0}\selectfont A
  \par
}
  
\end{document}
```
does.

I'll need some time to understand the problem.

**Comment by komascript** [comment]
Ah, now it is clear what happens:
```latex
\documentclass{article}
\usepackage[byselectfont]{setspaceenhanced}
\setstretch{1.05}
\begin{document}
\def\baselinestretch{1}
\fontsize{6}{0}\selectfont A
\end{document}
```
results in a division by zero. It's not easy to say, what to do, if the second argument of `\fontsize` is 0 or just << 1 or less than the baselineskip value. I think, best would be to ignore `byselectfont` if the baselineskip value is less than the fontsize value and document it as feature.

**Comment by Vasco-Da-Gama-png** [comment]
First of all thank you for your fast response. You wrote:

> Second: Please note, that `scrhack` is only a compatibility package for a deprecated KOMA-Script package. I recommend to use:

So do I not need it any longer? I continue developing and maintaining a LaTeX template written by a former collegue. He once added the scrhack package. I do not know, wheather I still need it or not. For our template, we have written our own class, which loads a lot of packages. Like hyperref, listings, floats, etc. So for all these packages scrhack isn't needed anymore?
If taking a look in our class would help, you can find it [here](https://collaborating.tuhh.de/m21/public/theses/itt-latex-template).

Now to your last two comments. I can't follow a 100% BUT the problem is connected with the latest release of TexLive.
We use a docker image to build our template weekly in gitlab CI/CD. This itself is monthly rebuilded. And since 01.11. the template isn't running anymore. I just tested my example with the image from october and it works just fine.
Links for the images:
Latest: registry.collaborating.tuhh.de/m21/public/theses/latex_dockerfile:latest
October version: registry.collaborating.tuhh.de/m21/public/theses/latex_dockerfile:2024-10
Hope this helps.

**Comment by komascript** [comment]
For `listings` you don't need `scrhack`, because Jobst has already added `tocbasic` support to `listings`.

For `hyperref` you don't need `scrhack` (for several years), because Heiko has fixed the issue with `hyperref` several years ago.

Instead of `float` you should use `floatbytocbasic` at least when using a KOMA-Script class or KOMA-Script package `tocbasic`, because KOMA-Script does not support the old `\float@addtolists` and `\float@listhead` interface any longer. It is too much work to keep a deprecated interface alive only because some package authors are not willing to adapt their packages and therefore do not support `tocbasic`.

Same for `floatrow` → `floatrowbytocbasic`. (So IMHO you should replace `floatrow` by `floatrowbytocbasic` in the class or your template.)

For `nomencl` you don't need `scrhack` any longer, because `nomencl` supports `tocbasic`.

Instead of `setspace` I always recommend `setspaceenhanced`, because of some general issues with `setspace`. See the `setspaceenhanced` documentation for more information.

Instead of `lscape` and `pdflscape` I always recommend `lscapeenchanded`, because of some general issues with `lscape`. See the `lscapeenhanced` documentation for more information.

If all the package authors would after my requests react like Jobs after my `listings` improvement request, the whole third-party-enchancement project with all the packages (inclusive `scrhack`) wouldn't be needed.
