### ISSUE TITLE
setspaceenhance doesn't correctly initialize some values

### ISSUE THREAD

**Issue by u-fischer** [komascript/third-party-enhancements#3]
**Describe the bug**

The following example gives a baselineskip of 0pt.

```latex
\documentclass{scrbook}
\usepackage{setspace}
\usepackage[byselectfont]{setspaceenhanced}

\ExplSyntaxOn
%\__setspaceenhanced_set_spacing:nn{1}{single}
\ExplSyntaxOff

\begin{document}
\showthe\baselineskip
xxx\\xxx
\end{document}
```

It results in the following messages from `log`-file:

```
> 0.0pt.
l.40 \showthe\baselineskip
```

~~~~
c:/texlive/2024/texmf-dist/tex/latex/setspaceenhanced/setspaceenhanced.sty
Package: setspaceenhanced 2024-11-05 v1.03 improved setspace package
~~~~

Remark: it works with book class but I didn't try to find out why. Also it doesn't necessarly affects a whole document - in the real document (where setspaceenhance was loaded through scrhack) only some tables were affected - probably because the class called setspace commands in various places..

**Comment by komascript** [comment]
Thank you for the report.

It seems these are even two issues:

* The result should be 13.6pt not 0.0pt.
* The new `scrhack` should not activate `byselectfont`, because the old hack file also doesn't do it.

A workaround the first issue would be:
```latex
\documentclass{scrbook}
\usepackage{setspace,scrhack}
\usepackage[byselectfont=false]{setspaceenhanced}% deactivate byselectfont
\ExplSyntaxOn
%\__setspaceenhanced_set_spacing:nn{1}{single}
\ExplSyntaxOff

\begin{document}
\showthe\baselineskip
xxx\\xxx
\end{document}
```

You have already found a workaround for the actual problem, whereby it would also suffice to load `setspaceenhanced` (or `setspace` when using `scrhack`) with the `singlespacing` option.

Maybe it is an initialization problem, but I have to do more investigation.

**Comment by komascript** [comment]
Thanks to your report I've found one more issue: `setspaceenhanced` does know all options of `setspace`.

**Comment by komascript** [comment]
@u-fischer Can you test your real document with the new developer version. If needed I can send you a new `setspaceenhanced.sty` via email.

**Comment by u-fischer** [comment]
As far as I can see it looks ok with the dev version (I installed everything with l3build).

**Comment by komascript** [comment]
Nice. Thank you again. I'll publish the new version soon.
